name: 'Airflow CI'

on:
  push:
    branches: [ 'feature/**' ]
    paths:
      - 'projects/data-market-sentiment/airflow/**'
  pull_request:
    paths:
      - 'projects/data-market-sentiment/airflow/**'

jobs:
  airflow-ci:
    name: 'Lint & Test Airflow'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python_version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest pandas pyarrow great-expectations
        pip install "apache-airflow[google,docker,standard]"

    - name: Lint with black
      run: black --check projects/data-market-sentiment/airflow/

    - name: Lint with flake8
      run: flake8 projects/data-market-sentiment/airflow/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      run: pytest projects/data-market-sentiment/airflow/tests/
