name: 'Terraform CI'

on:
  push:
    branches: [ 'feature/**' ]
    paths:
      - 'projects/data-market-sentiment/terraform/**'
  pull_request:
    paths:
      - 'projects/data-market-sentiment/terraform/**'

jobs:
  terraform-ci:
    name: 'Terraform Check & Plan'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./projects/data-market-sentiment/terraform/environments/dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Format
      run: terraform fmt -check -recursive ../..

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -no-color
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
